config/routes.rb
Rails.application.routes.draw do
  root controller: :documents, action: :index
  resources :documents do
    get 'versions/new'
    post 'versions', controller: :versions, action: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/key_concern.rb
module KeyConcern
  extend ActiveSupport::Concern

  included do
    after_initialize :add_key

    def add_key
      self.key ||= SecureRandom.hex
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  include KeyConcern
  has_many :versions, dependent: :destroy
end

app/models/version.rb
class Version < ApplicationRecord
  include KeyConcern

  belongs_to :document

  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new document_params

    version = Version.new
    version.file.attach version_params[:version][:file]

    @document.versions << version

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def version_params
      params
        .require(:document)
        .permit(
          version: [
            :file
          ]
        )
    end

    def document_params
      params
        .require(:document)
        .permit(
          :name,
          :description
        )
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_document, only: [:new, :create]
  def new
    @version = Version.new
  end

  def create
    version = Version.new
    version.file.attach version_params[:file]

    @document.versions << version
    @document.save

    redirect_to @document
  end

  private
    def set_document
      @document = Document.find(params[:document_id])
    end

    def version_params
      params
        .require(:version)
        .permit(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/documents/_form.html.haml
= form_with(model: document, local: true) do |form|
  - if document.errors.any?
    #error_explanation
      %h2
        = pluralize(document.errors.count, "error")
        prohibited this document from being saved:
      %ul
        - document.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name

  .field
    = form.label :description
    = form.text_field :description

  .field
    = form.fields :version do |fields|
      = fields.label :file
      = fields.file_field :file
  .actions
    = form.submit

app/views/documents/edit.html.haml
%h1 Editing Document
= render 'form', document: @document
= link_to 'Show', @document
|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%p#notice= notice
%h1 Documents
%table
  %thead
    %tr
      %th Key
      %th{:colspan => "3"}
  %tbody
    - @documents.each do |document|
      %tr
        %td= document.key
        %td= link_to 'Show', document
        %td= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New Document
= render 'form', document: @document
= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

= link_to 'Add New Version', document_versions_new_path(@document)

%p
  %strong Key:
  = @document.key
%p
  %strong Name:
  = @document.name
%p
  %strong Description:
  = @document.description

%hr

- @document.versions.each do |version|
  %p
    %span
      %strong Key:
      = version.key
    %span
      %strong File:
      = link_to :download, rails_blob_url(version.file, disposition: "attachment")
    %span
      = version.created_at

%p
  = link_to 'Back', documents_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Documentservice
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/versions/_form.html.haml
= form_with(scope: :version, url: document_versions_path, local: true) do |form|
  .field
    = form.label :file
    = form.file_field :file
  .actions
    = form.submit

app/views/versions/create.html.haml
%h1 Versions#create
%p Find me in app/views/versions/create.html.haml

app/views/versions/new.html.haml
%h3
  New version for document
  = @document.key

= render 'form'
= link_to 'Back', @document